version: '3.8'

services:  
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000        
        ports:
          - 8000:8000
        env_file:
          - ./.env.dev
        depends_on:
          - pgdb
    pgdb:
      image: postgres
      container_name: pgdb
      ports:
          - 5411:5432
      environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      volumes:
        - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:


  